version: "3.8"

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle_db
    environment:
      - ORACLE_PWD=MySecurePassword
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
